# Generated by Django 4.1.7 on 2023-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_informationrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationrequests',
            name='query_box',
            field=models.TextField(),
        ),
    ]
