# Generated by Django 4.1.7 on 2023-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_informationrequests_query_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='images/')),
                ('alumni_talk', models.TextField()),
            ],
        ),
    ]
