# Generated by Django 4.1.7 on 2023-03-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='facultypics/')),
                ('faculty_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='alumni',
            name='pic',
            field=models.ImageField(upload_to='alumniimages/'),
        ),
    ]
