# Generated by Django 4.1.7 on 2023-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_faculty_alter_alumni_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('ar', 'application_recieved'), ('co', 'contacted'), ('nc', 'not_contacted'), ('se', 'selected'), ('re', 'rejected')], default='ar', max_length=2),
        ),
    ]
