# Generated by Django 4.1.7 on 2023-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='course_interested',
            field=models.CharField(choices=[('Cth', 'certificate_in_theology'), ('Dth', 'diploma_in_theology'), ('Bth', 'bachelor_in_theology'), ('MD', 'masters_in_divinity')], default='Cth', max_length=4),
        ),
    ]
