# Generated by Django 4.1.7 on 2023-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_apply_course_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='course_interested',
            field=models.CharField(choices=[('Cth', 'certificate_in_theology'), ('Dth', 'diploma_in_theology'), ('Bth', 'bachelor_in_theology'), ('MD', 'masters_in_divinity')], default='Cth', max_length=150),
        ),
    ]
