# Generated by Django 4.1.7 on 2023-04-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_apply_course_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_department',
            field=models.TextField(default='department details'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_description',
            field=models.TextField(default='description details'),
        ),
    ]
