# Generated by Django 4.1.7 on 2023-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_faculty_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
