# Generated by Django 4.1.7 on 2023-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_faculty_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=4)),
                ('description', models.TextField(default='course details')),
                ('entry_requirements', models.TextField(default='entry requirements')),
                ('Period_of_study', models.TextField(default='enter details about period of study')),
                ('curriculum', models.TextField(default='enter details about curriculum')),
            ],
        ),
    ]
