# Generated by Django 4.1.7 on 2023-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_code',
            field=models.CharField(max_length=20),
        ),
    ]
