# Generated by Django 4.1.7 on 2023-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='video_title',
            field=models.TextField(default='enter title here'),
        ),
    ]
