# Generated by Django 4.1.7 on 2023-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_alter_youtubelink_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', models.ImageField(upload_to='podcastpics/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(default='enter text keep it a maximum of 2 lines')),
                ('spotify_podcast_link', models.URLField(null=True)),
                ('google_podcast_link', models.URLField(null=True)),
                ('apple_podcast_link', models.URLField(null=True)),
            ],
        ),
    ]
