# Generated by Django 4.1.7 on 2023-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_in_gallery', models.ImageField(upload_to='gallerypics/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='podcast',
            name='front_img',
            field=models.ImageField(null=True, upload_to='podcastpics/'),
        ),
    ]
