# Generated by Django 4.1.7 on 2023-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_photogallery_alter_podcast_front_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
