# Generated by Django 4.1.7 on 2023-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelorsintheology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='write about course in brief and only add data once ')),
                ('entry_requirements', models.TextField(default='entry requirements')),
                ('Period_of_study', models.TextField(default='enter details about period of study')),
                ('curriculum', models.TextField(default='enter details about curriculum')),
            ],
            options={
                'verbose_name_plural': 'Bachelors in Theology',
            },
        ),
        migrations.CreateModel(
            name='Certificateintheology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='write about course in brief and only add data once ')),
                ('entry_requirements', models.TextField(default='entry requirements')),
                ('Period_of_study', models.TextField(default='enter details about period of study')),
                ('curriculum', models.TextField(default='enter details about curriculum')),
            ],
            options={
                'verbose_name_plural': 'Certificates in Theology',
            },
        ),
        migrations.CreateModel(
            name='Diplomointheology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='write about course in brief and only add data once ')),
                ('entry_requirements', models.TextField(default='entry requirements')),
                ('Period_of_study', models.TextField(default='enter details about period of study')),
                ('curriculum', models.TextField(default='enter details about curriculum')),
            ],
            options={
                'verbose_name_plural': 'Diplomo in Theology',
            },
        ),
        migrations.CreateModel(
            name='MastersinDivinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='write about course in brief and only add data once ')),
                ('entry_requirements', models.TextField(default='entry requirements')),
                ('Period_of_study', models.TextField(default='enter details about period of study')),
                ('curriculum', models.TextField(default='enter details about curriculum')),
            ],
            options={
                'verbose_name_plural': 'Masters in Divinity',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='Period_of_study',
        ),
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='entry_requirements',
        ),
    ]
