# Generated by Django 4.1.7 on 2023-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_slider_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='give title', max_length=100),
        ),
    ]
