# Generated by Django 4.1.7 on 2023-04-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpagecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('history', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
    ]
