# Generated by Django 4.1.7 on 2023-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_aboutpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPageFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(default='description')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
