# Generated by Django 4.1.7 on 2023-04-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_admissionpagecontent_faq_delete_admissionpagefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfBelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(default='statement')),
            ],
        ),
    ]
