# Generated by Django 4.1.7 on 2023-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_statementofbelief'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementofbelief',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
