# Generated by Django 4.1.7 on 2023-04-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_post_managers_remove_post_status_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
