# Generated by Django 4.1.7 on 2023-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_rename_excerpt_post_summary_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='morecontent',
            field=models.TextField(default='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='summary'),
        ),
    ]
