# Generated by Django 4.1.7 on 2023-04-10 17:14

from django.db import migrations, models
import posting.models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_post_morecontent_alter_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='summary', validators=[posting.models.validate_word_count]),
        ),
    ]
